In [86]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [87]:
df = pd.read_csv('recursos-humanos_v1.csv',index_col=0)

In [88]:
df.shape

(311, 37)

In [89]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'Remuneration'],
      dtype='object')

In [90]:
def columnas_a_minusculas(df):
    """
    Cambia los nombres de las columnas a minusculas
    parametros:
    dataframe del que sacamos las columnas
    diccionario_columnas:Diccionario que mapea nombres de columnas a sus nuevos nombres
    return:
    dataframe modificado
    """
    df.columns = map(str.lower, df.columns)
    df.columns

    return df

In [91]:
df=columnas_a_minusculas(df)

In [92]:
df.columns

Index(['employee_name', 'empid', 'marriedid', 'maritalstatusid', 'genderid',
       'empstatusid', 'deptid', 'perfscoreid', 'fromdiversityjobfairid',
       'salary', 'termd', 'positionid', 'position', 'state', 'zip', 'dob',
       'sex', 'maritaldesc', 'citizendesc', 'hispaniclatino', 'racedesc',
       'dateofhire', 'dateoftermination', 'termreason', 'employmentstatus',
       'department', 'managername', 'managerid', 'recruitmentsource',
       'performancescore', 'engagementsurvey', 'empsatisfaction',
       'specialprojectscount', 'lastperformancereview_date', 'dayslatelast30',
       'absences', 'remuneration'],
      dtype='object')

In [93]:
#1: Admin Offices, 2: Executive Officer, 3: IT/IS, 4: Software engi, 5: Production, 6:Sales

In [94]:
def categorizar_department_id(df):
    """
    Esta función las siguientes columnas del dataframe() asigna valores
    transformados 
    Parámetros:
    Recibe un dataframe
    Returns:
    Devuelve el dataframe modificado
    """
    mapping = {
        1: 'Admin Offices',
        2: 'Executive Officer',
        3: 'IT/IS',
        4: 'Software Engineering',
        5: 'Production',
        6: 'Sales'
    }
    df['deptid'] = df['deptid'].map(mapping)
    return df

In [95]:
df= categorizar_department_id(df)

In [96]:
df_dep= df[['deptid','department']]

In [97]:
df_dep

                   deptid            department
0              Production     Production
1                   IT/IS                 IT/IS
2              Production     Production
3              Production     Production
4              Production     Production
5              Production     Production
6    Software Engineering  Software Engineering
7              Production     Production
8              Production     Production
9                   IT/IS                 IT/IS
10             Production                   NaN
11             Production                   NaN
12                  IT/IS                   NaN
13             Production                   NaN
14             Production     Production
15             Production                   NaN
16             Production                   NaN
17             Production                   NaN
18                  IT/IS                   NaN
19             Production                   NaN
20             Production                   NaN
21             Production     Production
22             Production     Production
23             Production     Production
24             Production     Production
25                  IT/IS                   NaN
26          Admin Offices         Admin Offices
27             Production                   NaN
28             Production                   NaN
29          Admin Offices         Admin Offices
30             Production                   NaN
31             Production     Production
32                  Sales                 Sales
33             Production     Production
34             Production                   NaN
35   Software Engineering  Software Engineering
36             Production                   NaN
37   Software Engineering  Software Engineering
38             Production                   NaN
39                  IT/IS                   NaN
40                  Sales                 Sales
41             Production     Production
42                  IT/IS                   NaN
43             Production     Production
44             Production     Production
45                  Sales                 Sales
46             Production     Production
47             Production     Production
48                  IT/IS                 IT/IS
49             Production                   NaN
50             Production                   NaN
51             Production     Production
52             Production     Production
53             Production     Production
54             Production     Production
55             Production     Production
56             Production     Production
57                  IT/IS                   NaN
58             Production                   NaN
59                  IT/IS                 IT/IS
60                  Sales                   NaN
61                  IT/IS                   NaN
62             Production     Production
63             Production     Production
64                  Sales     Production
65             Production                   NaN
66   Software Engineering  Software Engineering
67                  Sales                 Sales
68             Production                   NaN
69             Production                   NaN
70                  IT/IS                 IT/IS
71             Production     Production
72                  Sales                 Sales
73             Production     Production
74             Production                   NaN
75                  IT/IS                   NaN
76                  IT/IS                   NaN
77                  Sales                   NaN
78             Production                   NaN
79             Production     Production
80             Production     Production
81             Production                   NaN
82             Production     Production
83             Production     Production
84             Production                   NaN
85             Production     Production
86   Software Engineering                   NaN
87             Production                   NaN
88             Production     Production
89             Production     Production
90             Production     Production
91                  IT/IS                 IT/IS
92             Production                   NaN
93             Production     Production
94             Production     Production
95                  Sales                 Sales
96                  IT/IS                 IT/IS
97          Admin Offices                   NaN
98                  Sales                   NaN
99                  IT/IS                 IT/IS
100            Production     Production
101            Production     Production
102            Production     Production
103            Production     Production
104                 Sales                   NaN
105            Production                   NaN
106            Production                   NaN
107                 Sales                 Sales
108                 IT/IS                 IT/IS
109                 IT/IS                 IT/IS
110            Production     Production
111            Production     Production
112            Production     Production
113                 IT/IS                 IT/IS
114            Production     Production
115            Production     Production
116            Production     Production
117            Production                   NaN
118            Production     Production
119            Production     Production
120                 IT/IS                 IT/IS
121                 Sales                   NaN
122            Production                   NaN
123            Production     Production
124            Production                   NaN
125            Production     Production
126            Production     Production
127            Production     Production
128                 Sales                 Sales
129            Production     Production
130                 IT/IS                 IT/IS
131                 Sales                   NaN
132         Admin Offices                   NaN
133            Production     Production
134            Production     Production
135            Production                   NaN
136            Production     Production
137            Production     Production
138            Production                   NaN
139            Production     Production
140            Production     Production
141            Production                   NaN
142            Production                   NaN
143            Production     Production
144                 IT/IS                   NaN
145            Production                   NaN
146            Production                   NaN
147                 Sales                 Sales
148            Production                   NaN
149                 Sales                   NaN
150     Executive Officer      Executive Office
151            Production     Production
152            Production     Production
153            Production     Production
154            Production                   NaN
155                 Sales                 Sales
156                 IT/IS                 IT/IS
157            Production                   NaN
158            Production     Production
159            Production                   NaN
160         Admin Offices         Admin Offices
161            Production                   NaN
162                 IT/IS                   NaN
163            Production                   NaN
164         Admin Offices                   NaN
165            Production     Production
166                 Sales                   NaN
167            Production                   NaN
168            Production     Production
169            Production                   NaN
170                 IT/IS                 IT/IS
171            Production     Production
172            Production     Production
173            Production                   NaN
174            Production     Production
175            Production                   NaN
176            Production     Production
177            Production     Production
178            Production     Production
179            Production     Production
180  Software Engineering  Software Engineering
181            Production     Production
182            Production     Production
183            Production                   NaN
184                 Sales                 Sales
185            Production                   NaN
186            Production                   NaN
187            Production                   NaN
188            Production     Production
189            Production     Production
190                 IT/IS                 IT/IS
191            Production     Production
192            Production                   NaN
193                 IT/IS                   NaN
194            Production     Production
195            Production                   NaN
196            Production                   NaN
197                 IT/IS                   NaN
198            Production                   NaN
199            Production     Production
200            Production     Production
201            Production     Production
202                 Sales                   NaN
203            Production     Production
204            Production     Production
205            Production                   NaN
206            Production                   NaN
207                 Sales                 Sales
208            Production     Production
209            Production     Production
210                 Sales                 Sales
211            Production     Production
212  Software Engineering  Software Engineering
213                 IT/IS                 IT/IS
214            Production     Production
215            Production     Production
216            Production     Production
217            Production                   NaN
218            Production     Production
219            Production                   NaN
220                 IT/IS                   NaN
221            Production     Production
222            Production                   NaN
223                 Sales                 Sales
224            Production                   NaN
225            Production                   NaN
226            Production     Production
227         Admin Offices                   NaN
228                 IT/IS                 IT/IS
229            Production     Production
230                 Sales                 Sales
231            Production                   NaN
232            Production     Production
233            Production     Production
234            Production     Production
235            Production     Production
236            Production                   NaN
237            Production     Production
238                 IT/IS                 IT/IS
239                 IT/IS                   NaN
240                 IT/IS                   NaN
241            Production                   NaN
242            Production     Production
243                 IT/IS                 IT/IS
244                 IT/IS                 IT/IS
245  Software Engineering  Software Engineering
246            Production     Production
247            Production     Production
248            Production     Production
249                 IT/IS                 IT/IS
250            Production     Production
251            Production     Production
252                 IT/IS                 IT/IS
253            Production     Production
254                 IT/IS                   NaN
255         Admin Offices         Admin Offices
256            Production                   NaN
257            Production     Production
258                 Sales                 Sales
259         Admin Offices                   NaN
260            Production     Production
261                 IT/IS                 IT/IS
262                 IT/IS                 IT/IS
263            Production                   NaN
264            Production     Production
265            Production                   NaN
266            Production                   NaN
267                 Sales                   NaN
268         Admin Offices         Admin Offices
269            Production     Production
270                 Sales                 Sales
271            Production                   NaN
272            Production                   NaN
273            Production     Production
274  Software Engineering                   NaN
275                 IT/IS                   NaN
276            Production                   NaN
277            Production     Production
278                 Sales                 Sales
279            Production                   NaN
280            Production     Production
281            Production     Production
282                 Sales                 Sales
283            Production     Production
284                 IT/IS                   NaN
285  Software Engineering                   NaN
286            Production                   NaN
287                 IT/IS                 IT/IS
288                 Sales                   NaN
289            Production                   NaN
290            Production                   NaN
291                 Sales                   NaN
292                 IT/IS                 IT/IS
293            Production                   NaN
294            Production                   NaN
295            Production                   NaN
296            Production     Production
297            Production                   NaN
298                 IT/IS                 IT/IS
299                 IT/IS                   NaN
300            Production     Production
301            Production     Production
302            Production                   NaN
303            Production     Production
304            Production                   NaN
305            Production                   NaN
306            Production     Production
307            Production                   NaN
308                 IT/IS                   NaN
309                 IT/IS                 IT/IS
310            Production                   NaN

In [98]:
df.columns

Index(['employee_name', 'empid', 'marriedid', 'maritalstatusid', 'genderid',
       'empstatusid', 'deptid', 'perfscoreid', 'fromdiversityjobfairid',
       'salary', 'termd', 'positionid', 'position', 'state', 'zip', 'dob',
       'sex', 'maritaldesc', 'citizendesc', 'hispaniclatino', 'racedesc',
       'dateofhire', 'dateoftermination', 'termreason', 'employmentstatus',
       'department', 'managername', 'managerid', 'recruitmentsource',
       'performancescore', 'engagementsurvey', 'empsatisfaction',
       'specialprojectscount', 'lastperformancereview_date', 'dayslatelast30',
       'absences', 'remuneration'],
      dtype='object')

In [99]:
def renombrar_columna(df, nombre_anterior, nombre_nuevo):
    """
    Renombra una columna en el DataFrame
    Parametros:
    - df: DataFrame
    - nombre_anterior: Nombre actual de la columna que va a ser renombrada.
    - nombre_nuevo: Nombre nuevo de la columna.

    Returns:
    - DataFrame actualizado.
    """
    if nombre_anterior in df.columns:   
        df.rename(columns={nombre_anterior: nombre_nuevo}, inplace=True)
        return df
    else:
        return df

In [100]:
df = renombrar_columna(df,'dob','date_of_birth')
df = renombrar_columna(df,'department','xdepartment')

In [101]:
df= renombrar_columna(df,'deptid','department')

In [102]:
df.columns

Index(['employee_name', 'empid', 'marriedid', 'maritalstatusid', 'genderid',
       'empstatusid', 'department', 'perfscoreid', 'fromdiversityjobfairid',
       'salary', 'termd', 'positionid', 'position', 'state', 'zip',
       'date_of_birth', 'sex', 'maritaldesc', 'citizendesc', 'hispaniclatino',
       'racedesc', 'dateofhire', 'dateoftermination', 'termreason',
       'employmentstatus', 'xdepartment', 'managername', 'managerid',
       'recruitmentsource', 'performancescore', 'engagementsurvey',
       'empsatisfaction', 'specialprojectscount', 'lastperformancereview_date',
       'dayslatelast30', 'absences', 'remuneration'],
      dtype='object')

In [103]:
#lista_columnas = ['DateofHire','LastPerformanceReview_Date','TermReason','MarriedID','CitizenDesc','RecruitmentSource','PerfScoreID','ManagerID','Zip']
#lista_columnas = ['Zip']

In [104]:
def exploracion_inicial(df,lista_columnas):
    """Esta funcion hace una exploracion inicial de las columnas de un dataframe
        Parametros:
        df ... dataframe 
        lista_columnas .. lista de columnas del dataframe que hay que analizar
        return:
        nada, solamente lo analizamos y lo printeamos por pantalla para ir tomando decisiones"""
    for columna in lista_columnas:
        print('*********************************')
        print(f'Analizando la columna {columna}:')
        print(f'La cantidad de nulos es : {df[columna].isnull().sum()}')
        print(f'La columna es de tipo {df[columna].dtypes}')
        
        print(f'El porcentaje de nulos de esta columna es de  {df[columna].isnull().sum() / df.shape[0] * 100} %')
        print(f'Los valores unicos son: {df[columna].value_counts()}')
        print(f'Los composicion de la columna por valores es : { df[columna].value_counts()}')

In [105]:
#exploracion_inicial(df,lista_columnas)

In [106]:


# def dataframe_nulos(df, lista_columnas):
#     """Esta funcion coge un dataframe y una lista de columnas y crea otro dataframe con informacion resultante"""
    
#     # Creamos un diccionario vacío para almacenar los resultados
#     resultados = {}
    
#     for columna in lista_columnas:
#         # Calcular el porcentaje de valores nulos para la columna actual
#         porcentaje_nulos = round((df[columna].isnull().sum() / df.shape[0]) * 100,2)
        
#         # Obtener el tipo de datos de la columna actual
    
#         tipo = df[columna].dtypes
        
#         # Agregar la información al diccionario de resultados
#         resultados[columna] = {"Tipo": tipo, "%nulos": porcentaje_nulos}

#     # Creamo un dataFrame a partir del diccionario
#     df_resultado = pd.DataFrame(resultados).T
#     print(df_resultado)

In [107]:
#dataframe_nulos(df,lista_columnas)